FROM python:3.12-slim

WORKDIR /frontend

RUN python -m pip install --upgrade pip

COPY src/frontend/requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY src/frontend/. .

CMD ["python", "main.py"] 