FROM python:3.12-slim

WORKDIR /backend

RUN python -m pip install --upgrade pip

COPY src/backend/requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY src/backend/. .

CMD ["python", "main.py"]