FROM python:3.12-slim

WORKDIR /bot

RUN python -m pip install --upgrade pip

COPY src/bot/requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY src/bot/. .

CMD ["python", "main.py"] 