server {
  listen 80;

  location /webhooks {
    proxy_set_header Host $http_host;
    proxy_pass http://hrbot_bot:5000/;
  }

  location /api {
    proxy_set_header Host $http_host;
    proxy_pass http://hrbot_backend:8000/;
  }

  location / {
    proxy_set_header Host $http_host;
    proxy_pass http://hrbot_frontend:5005/;
  }
} 