from config import settings as s

SETTINGS_URL_PREFIX = '/settings'
MENU_URL_PREFIX = '/menu'
USERS_URL_PREFIX = '/users'
MESSAGES_URL_PREFIX = '/messages'
AUTH_URL_PREFIX = '/auth'

SETTINGS_PAGE_URL = s.URL_PREFIX + SETTINGS_URL_PREFIX
MENU_PAGE_URL = s.URL_PREFIX + MENU_URL_PREFIX
USERS_PAGE_URL = s.URL_PREFIX + USERS_URL_PREFIX
MESSAGES_PAGE_URL = s.URL_PREFIX + MESSAGES_URL_PREFIX
AUTH_PAGE_URL = s.URL_PREFIX + AUTH_URL_PREFIX
LOGIN_PAGE_URL = AUTH_PAGE_URL + '/login'
LOGOUT_PAGE_URL = AUTH_PAGE_URL + '/logout'
