"""is_active field for User

Revision ID: 1485a4002c67
Revises: 267ff4c31d08
Create Date: 2025-09-07 12:40:20.052476

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1485a4002c67'
down_revision: Union[str, Sequence[str], None] = '267ff4c31d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'auth_user',
        sa.Column(
            'is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'is_active')
    # ### end Alembic commands ###
