"""created/updated by fields

Revision ID: 20afba6b4019
Revises: 41a80f4dd9c4
Create Date: 2025-09-19 17:59:37.014043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20afba6b4019'
down_revision: Union[str, Sequence[str], None] = '41a80f4dd9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('auth_user', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'auth_user', 'auth_user', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'auth_user', 'auth_user', ['updated_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_user', type_='foreignkey')
    op.drop_constraint(None, 'auth_user', type_='foreignkey')
    op.drop_column('auth_user', 'updated_by_id')
    op.drop_column('auth_user', 'created_by_id')
    # ### end Alembic commands ###
