"""for deployment

Revision ID: 22c54785b00b
Revises: 
Create Date: 2025-10-16 21:10:40.056571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c54785b00b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_role',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('can_edit_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_edit_users', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_send_messages', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_edit_menu', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('setting',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('int_type', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.String(length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['auth_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_session',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expired_at', sa.DateTime(), server_default=sa.text("(NOW() + interval '3 days')"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_session_id'), 'auth_session', ['id'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('is_banned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), server_default=sa.text('null'), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['auth_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('button_text', sa.String(length=20), nullable=False),
    sa.Column('answer', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['auth_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('button_text')
    )
    op.create_table('messages',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=2048), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['auth_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('menu')
    op.drop_table('employees')
    op.drop_index(op.f('ix_auth_session_id'), table_name='auth_session')
    op.drop_table('auth_session')
    op.drop_table('auth_user')
    op.drop_table('setting')
    op.drop_table('auth_role')
    # ### end Alembic commands ###
