"""User & Role models

Revision ID: 267ff4c31d08
Revises: aa319a92e440
Create Date: 2025-09-06 19:18:41.209372

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '267ff4c31d08'
down_revision: Union[str, Sequence[str], None] = 'aa319a92e440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'auth_role',
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'auth_user',
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
    )
    op.alter_column(
        'setting',
        'int_type',
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text('false'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'setting',
        'int_type',
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text('false'),
    )
    op.drop_table('auth_user')
    op.drop_table('auth_role')
    # ### end Alembic commands ###
