"""permission fields for role model

Revision ID: 41a80f4dd9c4
Revises: 5e12a42f3c21
Create Date: 2025-09-18 13:47:47.058682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a80f4dd9c4'
down_revision: Union[str, Sequence[str], None] = '5e12a42f3c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_role', sa.Column('can_edit_settings', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('auth_role', sa.Column('can_edit_users', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('auth_role', sa.Column('can_send_messages', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('auth_role', sa.Column('can_edit_menu', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_role', 'can_edit_menu')
    op.drop_column('auth_role', 'can_send_messages')
    op.drop_column('auth_role', 'can_edit_users')
    op.drop_column('auth_role', 'can_edit_settings')
    # ### end Alembic commands ###
