"""messages

Revision ID: 9988c7daeb35
Revises: 20afba6b4019
Create Date: 2025-09-25 14:22:13.110794

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9988c7daeb35'
down_revision: Union[str, Sequence[str], None] = '20afba6b4019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'employees',
        sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('name', sa.String(length=256), nullable=True),
        sa.Column(
            'is_banned', sa.Boolean(), server_default=sa.text('false'), nullable=False
        ),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated_by_id', sa.Integer(), server_default=sa.text('null'), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['updated_by_id'], ['auth_user.id'], ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'messages',
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('text', sa.String(length=2048), nullable=False),
        sa.Column('manager_id', sa.Integer(), nullable=True),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['manager_id'], ['auth_user.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('employees')
    # ### end Alembic commands ###
