"""Setting table name change v2

Revision ID: aa319a92e440
Revises: b0117fc5068e
Create Date: 2025-09-04 08:42:26.559342

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aa319a92e440'
down_revision: Union[str, Sequence[str], None] = 'b0117fc5068e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'setting',
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column(
            'value', sa.String(length=255), server_default=sa.text("''"), nullable=True
        ),
        sa.Column(
            'int_type', sa.Boolean(), server_default=sa.text('false'), nullable=True
        ),
        sa.Column(
            'description',
            sa.String(length=255),
            server_default=sa.text("''"),
            nullable=True,
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.drop_table('botsettingsorm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'botsettingsorm',
        sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            'value',
            sa.VARCHAR(length=255),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'int_type',
            sa.BOOLEAN(),
            server_default=sa.text('false'),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'description',
            sa.VARCHAR(length=255),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('botsettingsorm_pkey')),
    )
    op.drop_table('setting')
    # ### end Alembic commands ###
