"""Model BotSettings name change

Revision ID: b0117fc5068e
Revises: d8782eec0d1d
Create Date: 2025-09-01 11:29:38.798240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0117fc5068e'
down_revision: Union[str, Sequence[str], None] = 'd8782eec0d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botsettingsorm',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('int_type', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('description', sa.String(length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('botsettings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botsettings',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('int_type', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('botsettings_pkey'))
    )
    op.drop_table('botsettingsorm')
    # ### end Alembic commands ###
