"""Initial

Revision ID: d8782eec0d1d
Revises: 
Create Date: 2025-08-22 16:17:25.650776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8782eec0d1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botsettings',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('int_type', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('description', sa.String(length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('botsettings')
    # ### end Alembic commands ###
